export const api = window.chrome || window.browser;

export const state = {
  settings: null,
  requests: [],
  filtered: [],
  selectedId: null,
  search: '',
  querySearch: '',
  payloadSearch: '',
  payloadExpand: 'level1',
  activeTab: 'payload',
  sessions: [],
  currentSessionId: null,
  sessionMode: 'new',
  sessionEditId: null,
  tabsCache: [],
  sites: [],
  allowlistServiceSearch: ''
};

export const elements = {
  sidebar: document.getElementById('sidebar'),
  openSidebar: document.getElementById('open-sidebar'),
  closeSidebar: document.getElementById('close-sidebar'),
  mobileOverlay: document.getElementById('mobile-sidebar-overlay'),
  requestList: document.getElementById('request-list'),
  requestCount: document.getElementById('request-count'),
  search: document.getElementById('search'),
  sessionList: document.getElementById('session-list'),
  newSession: document.getElementById('new-session'),
  clearSessions: document.getElementById('clear-sessions'),
  manageAllowlist: document.getElementById('manage-allowlist'),
  allowlistDialog: document.getElementById('allowlist-dialog'),
  allowlistServices: document.getElementById('allowlist-services'),
  allowlistFields: document.getElementById('allowlist-fields'),
  allowlistAdd: document.getElementById('allowlist-add'),
  enableHooks: document.getElementById('enable-hooks'),
  allowlistCancel: document.getElementById('allowlist-cancel'),
  allowlistSave: document.getElementById('allowlist-save'),
  sessionDialog: document.getElementById('session-dialog'),
  sessionDialogTitle: document.getElementById('session-dialog-title'),
  sessionNameInput: document.getElementById('session-name-input'),
  sessionSiteSelect: document.getElementById('session-site-select'),
  sessionSiteNew: document.getElementById('session-site-new'),
  sessionSiteInput: document.getElementById('session-site-input'),
  sessionSiteError: document.getElementById('session-site-error'),
  sessionLockTab: document.getElementById('session-lock-tab'),
  sessionCancel: document.getElementById('session-cancel'),
  sessionSave: document.getElementById('session-save'),
  emptyState: document.getElementById('empty-state'),
  observingState: document.getElementById('observing-state'),
  details: document.getElementById('details'),
  detailDomain: document.getElementById('detail-domain'),
  detailUrl: document.getElementById('detail-url'),
  detailMeta: document.getElementById('detail-meta'),
  detailQuery: document.getElementById('detail-query'),
  queryTools: document.getElementById('query-tools'),
  querySearch: document.getElementById('query-search'),
  detailPayload: document.getElementById('detail-payload'),
  detailHeaders: document.getElementById('detail-headers'),
  detailRaw: document.getElementById('detail-raw'),
  tabButtons: Array.from(document.querySelectorAll('.tab-button')),
  tabsSelect: document.getElementById('tabs-select'),
  payloadTools: document.getElementById('payload-tools'),
  payloadExpandTools: document.getElementById('payload-expand-tools'),
  payloadSearch: document.getElementById('payload-search'),
  sessionSummary: document.getElementById('session-summary'),
  confirmDialog: document.getElementById('confirm-dialog'),
  confirmCancel: document.getElementById('confirm-cancel'),
  confirmOk: document.getElementById('confirm-ok'),
  openHelp: document.getElementById('open-help'),
  helpDialog: document.getElementById('help-dialog'),
  helpClose: document.getElementById('help-close')
};
